### ISSUE TITLE
Duel timers.

### ISSUE THREAD

**Issue by blindndangerous** [tspivey/yugioh-game#145]
I understand that we get new people who need to learn how to duel, but I think that adding configurable timers for duels would be a great thing. I don't mind slower duels sometimes, but their are times when it can get crazy slow. If you're new, that's fine, but some of the older players I'd think know their decks. I also know that sighted games have these, such as Hearthstone and the sighted Yu-Gi-Oh clients. This could be just another option that you can set in your duel setups. I think 30 seconds to 3 minutes would be a good range.

**Comment by Timtam** [comment]
After talking to @blindndangerous and checking which things are possible we've come to the following conclusion:
Official Konami video games, as well as other official card game video games handle duel timers by ending the current player's turn on timeout.
The YGOPro core doesn't support such functionality. It doesn't support reverting current plays at all, or at least exiting from each action. Instead, there are irreversible actions which cannot be finished automatically, but need to be handleed by the player, like when you want to summon a monster, you also need to select attack or defense position and the slot to summon in.
Some of those situations can be answered automatically (like yes or no questions with no, or column position dialogs with some random answer), but others probably can't that easily (like ritual summon conditions with tributing monsters with at least level 9 or whatever).
YGOPro is also designed the way so that it automatically chains mandatory effects and stuff, leading in really long chains where the mechanism to end the turn needs to decide what to do and what not to do. And whenever your opponent needs to chain something, and he's afk as well, we got two stupid bots duelling each other until one of both ends up indeck empty losing or crashes/freezes (which is more likely to happen).
Well, the only alternative would be how the YGOPro client does it right now, and ending the duel as soon as one player hits the timeout. This is easily possible, but sounds rather harsh to me.
I'd consider this enhancement therefore as closed, maybe we will find a solution later or decide to implement the end duel solution. If anyone got any ideas, just comment below or contact via email or in-game.
