### ISSUE TITLE
MSG_SELECT_SUM fails

### ISSUE THREAD

**Issue by tspivey** [tspivey/yugioh-game#226]
MSG_SELECT_SUM still fails in some cases.

Disable deck shuffling (easiest way is to just add shuffle=False as the first line of Duel.load_deck) and import:

```
deck import test={"cards": [1278431, 1278431, 85991529, 1274455, 59496924, 1274455], "side": []}
```

Start the duel and special summon Kozmo Dark Planet on the first turn.
When it asks for the cards to banish, the correct answer is 1 2 3 (all of them). However, doing this fails with Levels out of range, and the only thing that can be done is to end the duel.

**Comment by melvinzhang** [comment]
The bug seems to be the check is based on all combinations of param[0] and param[1] for any pair of selected cards. However, in your example, we need to add the param of three cards together to get a high enough value. In ygopro, it is done recursively so it can handle any number of cards, see check_sel_sum_s found at https://github.com/Fluorohydride/ygopro/blob/master/gframe/client_field.cpp#L1224

**Comment by Timtam** [comment]
Might actually be related to #208.

**Comment by melvinzhang** [comment]
ygopro-core itself has similar checks on the response, 1) for exact case, https://github.com/Fluorohydride/ygopro-core/blob/master/playerop.cpp#L602 2) for at least case, https://github.com/Fluorohydride/ygopro-core/blob/master/playerop.cpp#L673

**Comment by tspivey** [comment]
I've hopefully fixed this for the at least case, but I'm not sure what cards I can use to test the other cases.

**Comment by Timtam** [comment]
@tspivey did you bring in the fix on the server already? whats the current status of that thing?

**Comment by tspivey** [comment]
I haven't seen any complaints about this recently. I'll reopen it if it breaks again.
