### ISSUE TITLE
Unable to install 'gsb'

### ISSUE THREAD

**Issue by ScullCandy72** [tspivey/yugioh-game#255]
When using the website [Replit](repl.it), I had to press run and install all the modules that the code didn't find, but when it told me it couldn't find the 'gsb' module, I typed the command, `pip install gsb`, and I got back an error saying the code can't install the module. Is there a way I can fix this?
![Screenshot 2020-12-01 at 11 52 34 AM](https://user-images.githubusercontent.com/72223608/100771143-0ed33600-33cc-11eb-9251-12adf9876f60.png)

**Comment by Timtam** [comment]
gsb is not on PyPI, we're just installing that from the GitHub repository too. I'd expect our game not to be runnable on replit, due to the requirements (you'll have to manually compile lua as well as the ygopro core with a C/C++ compiler in order to properly compile and launch our game). I'd be more productive to take some other idea into consideration, like installing a Windows Subsystem for Linux instance or getting a real Linux VM to work with.
