### ISSUE TITLE
show in watch

### ISSUE THREAD

**Issue by zironion** [tspivey/yugioh-game#40]
occasionally I see the opponent showing cards when it is player 1  instead of 0. 
this happens during watch.

**Comment by Timtam** [comment]
example please. Don't get what you mean.

**Comment by zironion** [comment]
so let's say someone uses a blue eyes deck. that person is on table 1, not table 2. instead of seeing fred show me a blueeyes dragon I'll see Lobo show me the card. the show hits and misses. I don't see it all the time but I do see it  occasionally and it only happens during watching a duel.

**Comment by Timtam** [comment]
I never encountered it. Probably confused because you always watch player 0, no matter whom you want to watch (yet). So you might at first expect to see player 1's position there, but you'll always get player 0's view, which seems wrong at first, but isn't.
Can be re-opened as soon as it happens again.
