### ISSUE TITLE
shuffling randomizer

### ISSUE THREAD

**Issue by zironion** [tspivey/yugioh-game#41]
consider tweaking the shuffling randomizer so that people don't just get spell/trap cards in hand and can not react to the opponent.
duels are lost when the randomizer only forks out spell/trap cards.

**Comment by Timtam** [comment]
first of all, thats not true. It always depends on the spell/trap cards you get. Second, this isn't gonna happen. You as the creator of that deck are responsible to find the right balance of your cards, and bad hands happen to everyone, not just in here, but in real life too, so we wanna stay as close as possible to real randomness instead of tweaking in rules which force you to draw monsters as well.
@tsp: please close here.

**Comment by Timtam** [comment]
haha
@tspivey, please close here
